version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.2
    - 8.2.4
    - 8.2.6
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.15
