language: node_js

sudo: false

node_js:
  - '10'

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

cache: npm

install:
  - npm install
  - lerna bootstrap

before_script:
  - lerna run build

script:
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
